version: 2
jobs:
  build:
    docker:
      - image: r1tschy/sailfishos-platform-sdk:3.0.3.9
    steps:
      - checkout
      - run: git submodule sync && git submodule update --init
      - run: git config user.email "circleci@nowhere.nowhere" && git config user.name "circleci"

      - restore_cache:
          keys:
            - venv-cache-{{ .Branch }}

      - run: mb2 -X -t SailfishOS-3.0.3.9-armv7hl build -d -j 2
      - store_artifacts:
          path: ~/project/RPMS/
          destination: rpms
      - run: mb2 -X -t SailfishOS-3.0.3.9-armv7hl make check

      - run: git clean -f -x
      - run: mb2 -X -t SailfishOS-3.0.3.9-i486 build -d -j 2
      - store_artifacts:
          path: ~/project/RPMS/
          destination: rpms

      - save_cache:
          key: venv-cache-{{ .Branch }}
          paths:
            - ~/project/installroot/venv-armv7hl
            - ~/project/installroot/venv-i486
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
